# Generated by Django 5.0.3 on 2024-03-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_is_docente_customuser_is_visitante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_visitante',
        ),
        migrations.AddField(
            model_name='customuser',
            name='apellido',
            field=models.CharField(default='Apellido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='correo_electronico',
            field=models.EmailField(default='correo_generico@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='departamento_admin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='departamento_docente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='estatus',
            field=models.CharField(blank=True, choices=[('activo', 'Activo'), ('egresado', 'Egresado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nombre',
            field=models.CharField(default='nombre', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='programa_academico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
